import { Piece, PieceData, PieceColor } from "piece.slint";

export struct BoardSquare {
    marked: bool,
}

export component Board {
    in property <color> square-color: #121212;
    in property <color> back-color: #FFFFFF;
    in property <color> marked-color: #e3dc5d;
    in property <color> border-color: #000000;

    in property <length> board-length;
    in property <{x: length, y: length}> center;

    in-out property <[PieceData]> pieces;
    in-out property <[BoardSquare]> squares;

    property <length> length-no-border: board-length * 96%;
    property <length> length-border: board-length - length-no-border;

    callback square-clicked(int);

    x: center.x - board-length / 2;
    y: center.y - board-length / 2;

    width: board-length;
    height: board-length;

    // Background
    Rectangle {
        background: back-color;
        x: parent.width * 2%;
        y: parent.height* 2%;

        width: length-no-border;
        height: length-no-border;

        border-radius: length-border * 75%;
    }

    // Border
    Rectangle {
        background: border-color;
        border-radius: length-border;

        z: -2;
    }


    pure function calc-square-x(index: int) -> length {
        mod(index, 4)
            * length-no-border * 25%
            + length-no-border * (mod(index, 8) < 4 ? 0% : 12.5%)
            + length-border / 2
    }

    pure function calc-square-y(index: int) -> length {
        floor(index / 4) * (length-no-border * 12.5%) + length-border / 2
    }

    property <length> square-size: length-no-border * 12.5%;
    for square[index] in squares: Rectangle {
        x: calc-square-x(index);
        y: calc-square-y(index);

	width: square-size;
	height: square-size;

	background: square.marked ? marked-color : square-color;

	TouchArea {
	    clicked => {
		square-clicked(index);
	    }
	}
    }

    for piece in pieces : Piece {
        data: piece;
        radius: square-size / 2 - 5px;
        pos: {
            x: calc-square-x(piece.index) + square-size / 2,
            y: calc-square-y(piece.index) + square-size / 2
        };
    }
}
