import { Board } from "board.slint";

export enum CurrentWindow {
    Start,
    Game,
}

export component GameWindow inherits Window {
    preferred-width: 400px;
    preferred-height: 400px;

    min-width: board.width;
    min-height: board.height;

    in property <CurrentWindow> window-state: CurrentWindow.Start;

    // Board property links
    callback clicked <=> board.square-clicked;
    in-out property pieces <=> board.pieces;
    in-out property squares <=> board.squares;

    property <length> board-length: self.height * 85%;
    board := Board {
        square-color: #352f3b;
        back-color: #e3e0a0;
        marked-color: #ffff41;
        board-length: parent.board-length;
        center: {x: parent.width / 2, y: parent.height / 2};
        visible: window-state == CurrentWindow.Game;
    }
}

