import { Button, VerticalBox } from "std-widgets.slint";

export component GameWindow inherits Window {
    width: 400px;
    height: 400px;
    point := Rectangle {
	background: #000000;

	width: 20px;
	height: 20px;

	x: parent.width / 2 - self.width / 2;
	y: parent.height / 2 - self.height / 2;
	animate x {
	     duration: 150ms;
	     easing: ease-in-out-quad;
	}
	animate y {
	     duration: 150ms;
	     easing: ease-in-out-quad;
	}
    }
    TouchArea {
	width: parent.width;
	height: parent.height;
	clicked => {
	    point.x = self.mouse-x;
	    point.y = self.mouse-y;
	}
    }
}

