import { Board } from "board.slint";

export component GameWindow inherits Window {
    preferred-width: 400px;
    preferred-height: 400px;

    min-width: board.width;
    min-height: board.height;

    // Board property links
    callback clicked <=> board.square-clicked;
    in-out property pieces <=> board.pieces;
    in-out property squares <=> board.squares;

    property <length> board-length: self.height * 85%;
    board := Board {
        square-color: #00FF00;
        back-color: #FFFF00;
        board-length: parent.board-length;
        center: {x: parent.width / 2, y: parent.height / 2};
    }
}

