export component Circle {
    in property <length> radius;

    in property <brush> color;

    property <length> diameter: radius * 2;

    height: diameter;
    width: diameter;

    Rectangle {
        border-radius: radius;
        background: color;
    }
}

export enum PieceColor {
    White,
    Black,
}

export struct PieceData {
    index: int,
    color: PieceColor,
    is-king: bool,
}

export component Piece {
    in property <PieceData> data;
    in property <length> radius;
    in property <{x: length, y: length}> pos;

    x: pos.x - radius;
    y: pos.y - radius;
    
    animate x, y {
         duration: 150ms;
         easing: ease-in-out;
    }

    width: radius * 2;
    height: radius * 2;

    Circle {
        radius: radius;
        color: data.color == PieceColor.White ? white : black;
    }
}

